services:
  db:
    image: postgres:15
    container_name: basilic-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  ponder:
    container_name: basilic-ponder
    build:
      context: ../apps/ponder
      dockerfile: Dockerfile
    restart: always
    ports:
      - "42069:42069"  # Default Ponder port
    environment:
      PONDER_DATABASE_URL: postgresql://postgres:postgres@basilic-db:5432/postgres
      PONDER_LOGGING_LEVEL: info
      NODE_ENV: development
    volumes:
      - ../apps/ponder:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:

    