## NOTE: This is a work in progress to integrate Supabase
#        or migrate entirely to Supabase.
#        This is not ready for production use.

services:
  db:
    container_name: basilic-db
    image: supabase/postgres:15.8.1.060
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../apps/supabase/db-data:/var/lib/postgresql/data  # Persist DB in `/apps/supabase/db-data`
      - ../apps/supabase/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql  # Init script
    networks:
      - basilic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  studio:
    container_name: basilic-studio
    image: supabase/studio:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SUPABASE_DATABASE_URL: postgres://postgres:postgres@basilic-db:5432/postgres
      SUPABASE_URL: http://localhost:8000
      SUPABASE_ANON_KEY: super-secret-key
      SUPABASE_SERVICE_ROLE_KEY: super-secret-role-key

  ponder:
    container_name: basilic-ponder
    build:
      context: ../apps/ponder
      dockerfile: Dockerfile
    restart: always
    ports:
      - "42069:42069"  # Default Ponder port
    environment:
      PONDER_DATABASE_URL: postgresql://postgres:postgres@basilic-db:5432/postgres
      PONDER_LOGGING_LEVEL: info
      NODE_ENV: development
    volumes:
      - ../apps/ponder:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy