[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path = "cache"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
