name: CI

on:
  push:
    paths:
      - "contracts/**"
  pull_request:
    paths:
      - "contracts/**"
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Authenticate Supabase CLI
        run: supabase link --project-id ${{ secrets.SUPABASE_PROJECT_ID }} --service-role-key ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Get Supabase Branch Connection URL
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF_NAME | sed 's/\//_/g')
          CONNECTION_URL=$(supabase db branches list --json | jq -r --arg BRANCH "$BRANCH_NAME" '.[] | select(.name == $BRANCH) | .connectionString')
          echo "SUPABASE_CONNECTION_URL=$CONNECTION_URL" >> $GITHUB_ENV

      - name: Cache Foundry Build Artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            foundry/cache
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-foundry-
          max-cache-size: 200MB

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge build
        run: forge build --sizes
        id: build

      - name: Run Forge tests with Supabase DB
        env:
          DATABASE_URL: ${{ env.SUPABASE_CONNECTION_URL }}
        run: forge test -vvv
        id: test
